#! /bin/bash
#PBS -q gpu
#PBS -j oe
#PBS -l select=1:ngpus=1
#PBS -l walltime=23:00:00
#PBS -N CS5242_Training
cd ${PBS_O_WORKDIR}/src
source activate CS5242
python $PBS_O_WORKDIR/src/train_cnn.py  --model_index 0 \
                                         --nb_epochs 1 \
                                         --batch_size 32 \
                                         --nb_neg 10 \
                                         --verbose 1 \
                                         --preprocess 0
